### ISSUE TITLE
insertFirst/Last/At with extended DoublyLinkedListNode

### ISSUE THREAD

**Issue by jrj2211** [datastructures-js/linked-list#20]
It would be very useful to be able to use the insert/remove functions with an object that extends DoublyLinkedListNode. I have a list of points on a path and already have a Point class. I extended the point class with DoublyLinkedListNode and when I try to insertFirst it gives me back a new Node with the value set to my Point class.

My suggestion is to check if the provided object is instanceof DoublyLinkedListNode and if so just use that. For my project I already have a ton of references to my point object and it would be a lot cleaner to be able to call next/prev on them then have a Node wrapper. This would also not break backwards compatibility.

Example change to library:
```
   insertFirst(newNode) {
    if(newNode instanceof DoublyLinkedListNode === false) {
      newNode = new DoublyLinkedListNode(value);
    }

    if (this.isEmpty()) {
      this._head = newNode;
      this._tail = newNode;
    } else {
      this._head.setPrev(newNode);
      newNode.setNext(this._head);
      this._head = newNode;
    }
    this._count += 1;
    return newNode;
  }
```

Example custom node:

```
export default class Pointextends DoublyLinkedListNode {
  constructor(frame, value) {
    super();
    this.frame = frame;
    this.value = value;
    this.handles = [
      { x: 0, y: 0 },
      { x: 0, y: 0 }
    ];
  }
}
  
const points = new DoublyLinkedList();
points.insertLast(new Point(1,10));
points.insertLast(new Point(2,15));
points.insertLast(new Point(3,8));

// No need for value if using custom linked list. Access properties directly
points.head().handles[0];
```

**Comment by eyas-ranjous** [comment]
hi @jrj2211 

I know this request has taken some time. It was not trivial in fact and required a major update for the library. I finally got time to work it out, so the good news is that now LinkedList & DoublyLinkedList can be used with custom node types so you can do this in v6.0.0

```js
class Point extends DoublyLinkedListNode {
  constructor(frame) {
    super();
    this.frame = frame;
    this.handles = [
      { x: 0, y: 0 },
      { x: 0, y: 0 }
    ];
  }
}

const points = new DoublyLinkedList();
points.insertLast(new Point(1,10)); // works!
points.insertLast(new Point(2,15));
points.insertLast(new Point(3,8));

points.head().handles[0]; // works!
``` 

Cheers!

**Comment by jrj2211** [comment]
@eyas-ranjous Thank you!! Not a problem, I sidelined the project that I was using this library on but in the next couple months will be working on it again so this will be great to have.
