### ISSUE TITLE
Typing: toArray now returns nodes

### ISSUE THREAD

**Issue by mrwensveen** [datastructures-js/linked-list#31]
Both LinkedList and DoublyLinkedList.toArray now return LLNode and DLLNode instead of the node values. This is a breaking change and broke my code, but that's not the issue (I'll live :) )

linkedList.d.ts and doublyLinkedList.d.ts still define toArray as returning `T[]` which is false. This should be changed to reflect the change in behavior.

Also, I am a little curious as to why the behavior was changed.

**Comment by mrwensveen** [comment]
Hi. Did you get a chance to look at my PR? Let me know if you have any improvements or changes you want me to make.

**Comment by eyas-ranjous** [comment]
fix is released v6.1.1

**Comment by mrwensveen** [comment]
Thanks!
