### ISSUE TITLE
Custom LinkedList type not applied to find function's node parameter

### ISSUE THREAD

**Issue by EthanL06** [datastructures-js/linked-list#34]
The type I apply to my `LinkedList` is not being applied to the `node` parameter for the `find` function

Here I defined my `LinkedList` with a class I made called `Link`:
```typescript
import { LinkedList, LinkedListNode } from "@datastructures-js/linked-list";

class Link extends LinkedListNode {
    title: string;
    src: string;

    constructor(title: string, src: string) {
        super();
        this.title = title;
        this.src = src;
    }

    toString() {
        return this.title;
    }
}

const list = new LinkedList<Link>()
```
Now when I use the `find` function on `list`, I get an error with TypeScript:
```typescript
const list = new LinkedList<Link>();
list.find((node) => node.title === "Test"); // Property 'title' does not exist on type 'LinkedListNode'.
```

This is because the `node` parameter's type is still `LinkedListNode` and not being updated to `Link`
![image](https://github.com/datastructures-js/linked-list/assets/21349255/ffd1f74d-d1f2-47a3-b902-59b680b6df90)

The only fix for this is to cast `node` as a `Link`:
```typescript
const list = new LinkedList<Link>();
list.find((node: Link) => node.title === "Test"); // Now works
```

It would be nice if the `node` parameter automatically casts to the `LinkedList` type instead of having to manually do it

**Comment by eyas-ranjous** [comment]
@EthanL06 fix is released. v6.1.2
